name: Maven Build
description: Composite Action for Maven
inputs:
  jdk-distribution:
    description: JDK distribution to use (https://github.com/actions/setup-java?tab=readme-ov-file#supported-distributions)
    required: false
    default: corretto
  jdk-version:
    description: JDK version to use (https://github.com/actions/setup-java?tab=readme-ov-file#supported-version-syntax)
    required: false
    default: '21'
  pom-file:
    description: Pom file path
    required: false
    default: ./pom.xml
  mvn-goals:
    description: 'Maven goals to execute'
    required: false
    default: clean package
  mvn-opts:
    description: Maven Opts to configure
    required: false
    default: -Xmx2048m
runs:
  using: "composite"
  steps:
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.jdk-distribution }}
        java-version: ${{ inputs.jdk-version }}
        cache: maven

    - name: Maven Build
      shell: bash
      id: random-number-generator
      env:
        MAVEN_OPTS: ${{ inputs.mvn-opts }}
      run: |
        mvn -B -U ${{ inputs.mvn-goals }} -f ${{ inputs.pom-file }}

    - name: Find and Zip Artifact
      shell: bash
      run: |
        target_dir=$(find . -type d -name "target" | head -n 1)
        if [ -z "$target_dir" ]; then
          echo "No target directory found!"
          exit 1
        fi

        artifact=$(find "$target_dir" -type f \( -name "*.jar" -o -name "*.ear" -o -name "*.war" \) | head -n 1)
        if [ -z "$artifact" ]; then
          echo "No artifact found!"
          exit 1
        fi
        zip -j artifact.zip "$artifact"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: artifact.zip
