name: "Test Composite Action with all inputs"
on: 
  push:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute Composite Action
        uses: ./ # Usa la acción desde el repositorio actual
        with:
          jdk-distribution: corretto
          jdk-version: 21
          pom-file: test-action/pom.xml
          mvn-goals: clean package
          mvn-opts: -Xmx2048m